[package]
name = "monkey"
version = "0.1.0"
authors = ["Reto Habl√ºtzel <rethab@protonmail.ch>"]
edition = "2018"

[dev-dependencies]
tempfile="3.1"
# enable to run benchmarks: criterion = "0.3"

[[bench]]
name = "fib"
harness = false
