[package]
name = "monkey-interpreter"
version = "0.1.0"
authors = ["Reto Habl√ºtzel <rethab@protonmail.ch>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
